//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Res.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ResParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IResListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] ResParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] ResParser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectList([NotNull] ResParser.ObjectListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectList([NotNull] ResParser.ObjectListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] ResParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] ResParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.flagSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlagSpecifier([NotNull] ResParser.FlagSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.flagSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlagSpecifier([NotNull] ResParser.FlagSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] ResParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] ResParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ResParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectBody([NotNull] ResParser.ObjectBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ResParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectBody([NotNull] ResParser.ObjectBodyContext context);
}
